### ISSUE TITLE
api /release response structure has changed?

### ISSUE THREAD

**Issue by dnmfarrell** [metacpan/metacpan-api#745] opened 2017-11-06 14:06 UTC
It appears the `/release` endpoint is wrapping the returned data in an extra `release` object. E.g.

```
{
   "took" : 4,
   "release" : {
    ...
   },
   "total" : 1
}
```

Example [link](https://fastapi.metacpan.org/v1/release/GIBUS/RT-Extension-GroupSummary-0.01).

Perhaps GH-731 (in particular the release controller [change](https://github.com/metacpan/metacpan-api/commit/c98928d249e10a965f1cbadb2d3ef34bd7860536#diff-e13df266642bf9ea230baa1796f295fb))  caused this?

**Comment by mickeyn** [comment] 2017-11-06 15:27
where is the problem?

**Comment by dnmfarrell** [comment] 2017-11-06 15:32
@mickeyn Are you asking "where is the problem in the code?" or "what's the issue? (I don't see one)" or something different?

**Comment by mickeyn** [comment] 2017-11-06 15:34
I meant what the issue is? sorry for not being clear

The description was just pointing out a change, but not mentioning what (if anything) is broken by it.

**Comment by dnmfarrell** [comment] 2017-11-06 15:40
NP, I think it's an issue to change the structure of the api response. Such a change would break all consumers of the api endpoint.

**Comment by dnmfarrell** [comment] 2017-11-06 15:44
As additional context, if you look at the other endpoints, such as

-  [author](https://fastapi.metacpan.org/v1/author/DFARRELL)
- [module](https://fastapi.metacpan.org/v1/module/Data::Dumper)
- [distribution](https://fastapi.metacpan.org/v1/distribution/Data-Dumper)

They don't wrap the response in `author { ... }`  or `module{ ... }` or `distribution { ... }`.

**Comment by mickeyn** [comment] 2017-11-06 16:04
We are aware of this situation.

While I generally agree with your comments, this API is currently going through a major change phase - most of it didn't even exist until recently and it is not yet finalized (the reasons for how it currently is are to do with moving some functionality from the UI as is to the backend, but we haven't organized it yet. in the coming hackathon for MetaCPAN this will be discussed and a plan will be laid to the future of the API).

**Comment by dnmfarrell** [comment] 2017-11-06 16:23
Thanks for that context. I have no problem with the new endpoint structure and am grateful that metacpan provides an api. I use it to generate the data for my "What's new on CPAN" blog posts. 

I do think it would be easier on users of the API if an endpoint is going to change materially (ie breaking backwards compatibility) then the version number should change too. The change should also be  documented - I don't see any changes to the documentation, nor in the the pull request which indicate this change was going to occur. It looks like a bug.

WRT to my own needs, I've updated my code to handle the new endpoint, so this is not an urgent issue for me, but there may be other users who are impacted.

Thanks for looking into it.

**Comment by oalders** [comment] 2017-11-06 16:30
I don't think we should be wrapping established v1 endpoints without a version bump.  The unadvertised endpoints are beta as far as I'm concerned.  I didn't realize that's what was happening here. I apologize for missing that.

**Comment by mickeyn** [comment] 2018-08-08 10:35
closing. please reopen if there's something further we need to do here.

**Closed by mickeyn** 2018-08-08 10:35 UTC
