### ISSUE TITLE
Class-Multimethods missing version (1.701)

### ISSUE THREAD

**Issue by bmckalla** [metacpan/metacpan-api#808] opened 2018-05-16 14:31 UTC
https://fastapi.metacpan.org/v1/release
{ "query": { "match": { "distribution": "Class-Multimethods" } } }

Only returns up to 1.700. In addition, that archive for that listed version is "Class-Multimethods-1.701.tar.gz"

**Comment by haarg** [comment] 2018-06-03 14:58
Dupe of #809.

**Closed by haarg** 2018-06-03 14:58 UTC
