### ISSUE TITLE
Getopt-Euclid has incorrect versions

### ISSUE THREAD

**Issue by bmckalla** [metacpan/metacpan-api#810] opened 2018-05-16 14:42 UTC
{
  "query": {
      "bool": {
          "must": [{"term": {"distribution": "Getopt-Euclid"}}]
          }
    },
  "fields": ["version", "name"],
  "size": 37
}

**Comment by haarg** [comment] 2018-06-03 15:00
Dupe of #809.

**Closed by haarg** 2018-06-03 15:00 UTC
