### ISSUE TITLE
Incorrect distribution link from pod page

### ISSUE THREAD

**Issue by abh** [metacpan/metacpan-api#1021] opened 2021-06-09 02:12 UTC
On https://metacpan.org/pod/Beanstalk::Client the breadcrumb link to "Beanstalk-Client-1.07" goes to `https://dist/Beanstalk-Client` rather than the proper relative link.

It looks like the bug is a double `//` prefix in the URL.

**Comment by haarg** [comment] 2021-06-09 02:35
One of the servers hadn't properly updated to the fixed code. Fixed now.

**Closed** 2021-06-09 02:36 UTC

**Comment by neilb** [comment] 2021-06-09 12:26
I'm still getting this, for example on https://metacpan.org/pod/Lab::Measurement, but I don't a dodgy URL when looking at https://metacpan.org/pod/Dist::Zilla

Caching?

**Comment by haarg** [comment] 2021-06-09 15:49
That's probably caching in your browser.

**Comment by oalders** [comment] 2021-06-09 15:52
Not the answer you're looking for, but `curl -XPURGE  https://metacpan.org/pod/Lab::Measurement` can clear up individual pages. That's a good way to check if the issue is at the Fastly layer.

**Comment by haarg** [comment] 2021-06-09 15:57
Fixed.
